# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-26 00:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timerecord',
            options={},
        ),
    ]
