# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-26 01:38
from __future__ import unicode_literals

from django.db import migrations
import thresher.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0002_auto_20180226_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timerecord',
            name='door_in',
            field=thresher.fields.CharFactField(max_length=500),
        ),
        migrations.AlterField(
            model_name='timerecord',
            name='door_out',
            field=thresher.fields.CharFactField(max_length=500),
        ),
    ]
